
server:
  port: 8181
  contextPath: /uaa

security:
  user:
    password: password
  enable-csrf: false
  ignored: /resources/**
#logging:
#  level:
#    org.springframework.security: DEBUG

spring:
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
    

eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8181
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:user1234@localhost:8260/eureka  