server:
  port: 18080
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.114/config/spring-config-server-repo.git
          username: config
          password: config123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8260/eureka
          