server:
  port: 8989
  contextPath: /client

security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      accessTokenUri: http://localhost:8181/uaa/oauth/token
      userAuthorizationUri: http://localhost:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
      scope: openid    
